/**
 * 道具列表
 * 道具可以出售可以购买，部分仅能刷怪掉落
 * PS: 这个只是方便web展示，你修改这里的数值没有用哦
 */

// 材料类
const StuffList = [
  {
    name: "香蚀草",
    type: "stuff",
    detail: "魔兽山脉里的普通药草，炼制神行丸的材料之一",
    obtain: "历练",
    price: 60,
    recovery: 10,
  },
  {
    name: "噬蔓花",
    type: "stuff",
    detail: "魔兽山脉里的普通药草，炼制神行丸的材料之一",
    obtain: "历练",
    price: 60,
    recovery: 10,
  },
  {
    name: "千金藤",
    type: "stuff",
    detail: "魔兽山脉里的普通药草，炼制大力丸的材料之一",
    obtain: "历练",
    price: 60,
    recovery: 10,
  },
  {
    name: "活气果",
    type: "stuff",
    detail: "魔兽山脉里的普通药草，炼制大力丸的材料之一",
    obtain: "历练",
    price: 60,
    recovery: 10,
  },
  {
    name: "千年人参",
    type: "stuff",
    detail: "魔兽山脉里的普通药草，炼制活血丹的必要材料",
    obtain: "历练",
    price: 100,
    recovery: 50,
  },
];
// 丹药类
const YaoList = [
  {
    name: "神行丸",
    type: "yao",
    detail: "使用后下次吐纳经验翻倍",
    obtain: "商城购买/炼药",
    price: 500,
    recovery: 50,
  },
  {
    name: "大力丸",
    type: "yao",
    detail: "使用后下次历练经验翻倍",
    obtain: "商城购买/炼药",
    price: 500,
    recovery: 50,
  },
  {
    name: "活血丹",
    type: "yao",
    detail: "使用后可从重伤状态恢复",
    obtain: "商城购买/炼药",
    price: 5000,
    recovery: 500,
  },
  {
    name: "引魔香",
    type: "yao",
    detail: "使用后增加下次历练遇魔兽几率",
    obtain: "商城购买/炼药",
    price: 1000,
    recovery: 100,
  },
  {
    name: "五行丹",
    type: "yao",
    detail: "可随机重置斗气属性",
    obtain: "商城购买",
    price: 50000,
    recovery: 0,
  },
  {
    name: "洗髓丹",
    type: "yao",
    detail: "可提高血脉等级最高到玄阶高级",
    obtain: "商城购买/历练",
    price: 640000,
    recovery: 0,
  },
  {
    name: "高级洗髓丹",
    type: "yao",
    detail: "可提高血脉等级最高到地阶高级",
    obtain: "商城购买/历练",
    price: 1280000,
    recovery: 0,
  },
  {
    name: "天阶洗髓丹",
    type: "yao",
    detail: "可提高血脉等级最高到天阶高级",
    obtain: "商城购买/活动",
    price: 10240000,
    recovery: 0,
  },
  {
    name: "棒棒糖",
    type: "yao",
    detail: "儿童节特供，使用后立即获得2333经验",
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "粽子",
    type: "yao",
    detail: "端午节特供，使用后可重置历练次数",
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "月饼",
    type: "yao",
    detail: "中秋节特供，使用后可重置双修副本次数",
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "喜糖",
    type: "yao",
    detail: "结缘奖励，使用后可重置吐纳次数",
    obtain: "结缘",
    price: 0,
    recovery: 0,
  },
  {
    name: "传承丹",
    type: "yao",
    detail: "使用后再次重生时可完整保留本轮经验和功法",
    obtain: "未知",
    price: 0,
    recovery: 0,
  },
  {
    name: "断情散",
    type: "yao",
    detail: "使用后可与当前道侣绝交",
    obtain: "商城购买",
    price: 100000,
    recovery: 100,
  },
  {
    name: "借道悟真丹",
    type: "yao",
    detail: "以毕生功力为引，推演天阶功法。逆天而行，使用后获得天阶功法[太玄经]。(仅限斗圣以上级别使用)",
    obtain: "商城购买",
    price: 1500000,
    recovery: 0,
  },
];
// 功法类
const GongList = [
  {
    name: "八九玄功",
    type: "gong",
    detail: "地阶高级功法，一世之尊中主角孟奇所修炼的功法，修炼成功者可肉提成圣，不死不灭，拥有三头六臂和法天象地等大神通。",
    obtain: "商城购买",
    price: 1500000,
    recovery: 0,
  },
  {
    name: "不死神功",
    type: "gong",
    detail: "地阶高级功法，周维清所修炼的功法，修炼条件苛刻，但成功后可与天地同寿，拥有不死神罡。",
    obtain: "商城购买",
    price: 1500000,
    recovery: 0,
  },
  {
    name: "永生之术",
    type: "gong",
    detail: "天阶低级功法，林铭所修炼的功法，修炼成功可融合永恒之魂，永存于天地之间。",
    obtain: "商城购买",
    price: 3000000,
    recovery: 0,
  },
  {
    name: "天龙心法",
    type: "gong",
    detail: "天阶中级功法，古尘沙修炼的功法，超出了武功道术的范围，包含所有文明，能凝聚真神之位。",
    obtain: "商城购买",
    price: 15000000,
    recovery: 0,
  },
  {
    name: "焚决",
    type: "gong",
    detail: "天阶高级功法，别问，问就是最屌",
    obtain: "商城购买",
    price: 30000000,
    recovery: 0,
  },
];
// 武器类
const ArmsList = [
  {
    name: "屠龙宝刀",
    detail: "屠龙宝刀长约四尺，有百余斤重，锋利至极，无坚不摧，具备强力磁性能吸天下所有暗器。",
    obtain: "商城",
    type: "arms",
    atk: 100,
    def: 0,
    price: 1000000,
    recovery: 100,
  },
  {
    name: "玄铁剑",
    detail: "铁匠用上古玄铁炼成的剑，好像很锋利的样子。",
    obtain: "商城",
    type: "arms",
    atk: 15,
    def: 0,
    price: 3000,
    recovery: 750,
  },
  {
    name: "铁剑",
    detail: "铁匠用普通的铁炼成的剑，好像很锋利的样子。",
    obtain: "商城",
    type: "arms",
    atk: 15,
    def: 0,
    price: 2000,
    recovery: 500,
  },
  {
    name: "新手剑",
    detail: "新手都有的剑，攻击+2",
    type: "arms",
    obtain: "新手大礼包",
    atk: 1,
    def: 0,
    price: 1,
    recovery: 1,
  },
];
// 防具类
const ArmorList = [
  {
    name: "玄铁甲",
    detail: "铁匠用上古玄铁炼成的甲，好像很结实的样子。",
    obtain: "商城",
    type: "armor",
    atk: 0,
    def: 15,
    price: 3000,
    recovery: 750,
  },
  {
    name: "布甲",
    detail: "普通的布甲我们普通的摇。",
    obtain: "商城",
    type: "armor",
    atk: 0,
    def: 5,
    price: 1000,
    recovery: 250,
  },
  {
    name: "铁甲",
    detail: "普通的铁甲我们普通的摇。",
    obtain: "商城",
    type: "armor",
    atk: 0,
    def: 10,
    price: 2000,
    recovery: 500,
  },
  {
    name: "新手服",
    detail: "新手都有的初始套装，防御+2",
    type: "armor",
    obtain: "新手大礼包",
    atk: 0,
    def: 2,
    price: 1,
    recovery: 1,
  },
];
// 异火
const FireList = [
  {
    name: "帝炎",
    type: "fire",
    detail: "曾有异火拥有灵智后，吞尽其他火焰，自命帝炎，成丹率增加200%，攻击力增加200%",
    obtain: "未知",
    atk: 2,
    price: 0,
    recovery: 0,
  },
  {
    name: "虚无吞炎",
    type: "fire",
    detail: "生于虚无之中，可吞天噬地，成丹率增加130%，攻击力增加130%",
    obtain: "未知",
    atk: 1.3,
    price: 0,
    recovery: 0,
  },
  {
    name: "净莲妖火",
    type: "fire",
    detail: "有净化万物的特效，可将敌人变成火奴，成丹率增加120%，攻击力增加120%",
    obtain: "未知",
    atk: 1.2,
    price: 0,
    recovery: 0,
  },
  {
    name: "金帝焚天炎",
    type: "fire",
    detail: "古族传承之火，号称连斗气都可燃烧，成丹率增加110%，攻击力增加110%",
    obtain: "未知",
    atk: 1.1,
    price: 0,
    recovery: 0,
  },
  {
    name: "生灵之焱",
    type: "fire",
    detail: "长寿之火，充斥着生命之力，不擅长战斗，却可以催生药材，成丹率增加100%，攻击力增加80%",
    obtain: "未知",
    atk: 1,
    price: 0,
    recovery: 0,
  },
  {
    name: "八荒破灭焱",
    type: "fire",
    detail: "原炎族所拥有的最高异火，成丹率增加90%，攻击力增加90%",
    obtain: "未知",
    atk: 0.95,
    price: 0,
    recovery: 0,
  },
  {
    name: "九幽金祖火",
    type: "fire",
    detail: "原为九幽地冥族持有，后落入炎族之手，成丹率增加85%，攻击力增加85%",
    obtain: "未知",
    atk: 0.9,
    price: 0,
    recovery: 0,
  },
  {
    name: "红莲业火",
    type: "fire",
    detail: "深红且妖艳的火焰，火苗蹿升间，形成道道红莲，成丹率增加80%，攻击力增加80%",
    obtain: "未知",
    atk: 0.85,
    price: 0,
    recovery: 0,
  },
  {
    name: "三千焱炎火",
    type: "fire",
    detail: "又称三千星空焱炎火，成形于星空，能吸收星辰之力变强大，成丹率增加75%，攻击力增加75%",
    obtain: "未知",
    atk: 0.8,
    price: 0,
    recovery: 0,
  },
  {
    name: "九幽风炎",
    type: "fire",
    detail: "诞生于无尽深渊之中，成型于风罡最烈之地，成丹率增加70%，攻击力增加70%",
    obtain: "未知",
    atk: 0.75,
    price: 0,
    recovery: 0,
  },
  {
    name: "骨灵冷火",
    type: "fire",
    detail: "极寒与极热相结合的奇特火焰，成丹率增加65%，攻击力增加65%",
    obtain: "击败药尘即可获得",
    atk: 0.7,
    price: 0,
    recovery: 0,
  },
  {
    name: "九龙雷罡火",
    type: "fire",
    detail: "焚炎谷传承数百年的火焰，隐隐间有着龙威凝聚，成丹率增加60%，攻击力增加60%",
    obtain: "未知",
    atk: 0.65,
    price: 0,
    recovery: 0,
  },
  {
    name: "龟灵地火",
    type: "fire",
    detail: "形如巨龟的褐色奇异火焰，成丹率增加55%，攻击力增加55%",
    obtain: "未知",
    atk: 0.6,
    price: 0,
    recovery: 0,
  },
  {
    name: "陨落心炎",
    type: "fire",
    detail: "火由心生，淬气炼骨，号称修炼作弊器的无色火焰，吐纳经验增加50%，攻击力增加50%",
    obtain: "未知",
    atk: 0.55,
    price: 0,
    recovery: 0,
  },
  {
    name: "海心焰",
    type: "fire",
    detail: "深蓝色火焰极为玄异，火焰升腾如清澈海水般，成丹率增加45%，攻击力增加45%",
    obtain: "未知",
    atk: 0.5,
    price: 0,
    recovery: 0,
  },
  {
    name: "火云水炎",
    type: "fire",
    detail: "原炎族长老所有，成丹率增加40%，攻击力增加40%",
    obtain: "未知",
    atk: 0.45,
    price: 0,
    recovery: 0,
  },
  {
    name: "火山石焰",
    type: "fire",
    detail: "原炎族所有的暗红色火焰，成丹率增加35%，攻击力增加35%",
    obtain: "未知",
    atk: 0.4,
    price: 0,
    recovery: 0,
  },
  {
    name: "风怒龙炎",
    type: "fire",
    detail: "生于古老沙漠的龙卷风风眼中，风与火形态相结合，成丹率增加30%，攻击力增加30%",
    obtain: "未知",
    atk: 0.35,
    price: 0,
    recovery: 0,
  },
  {
    name: "青莲地心火",
    type: "fire",
    detail: "地心熔岩中的火焰，可形成火山爆发般的毁灭力量，成丹率增加25%，攻击力增加25%",
    obtain: "未知",
    atk: 0.3,
    price: 0,
    recovery: 0,
  },
  {
    name: "幽冥毒火",
    type: "fire",
    detail: "上古幽冥毒泽中的火焰，由毒瘴喂养成灵，含有剧毒，成丹率增加20%，攻击力增加20%",
    obtain: "未知",
    atk: 0.25,
    price: 0,
    recovery: 0,
  },
  {
    name: "阴阳双炎",
    type: "fire",
    detail: "万物本源所幻化的黑白两色火焰，拥有生命和死亡双重力量，成丹率增加15%，攻击力增加15%",
    obtain: "未知",
    atk: 0.2,
    price: 0,
    recovery: 0,
  },
  {
    name: "万兽灵火",
    type: "fire",
    detail: "由万兽之魂与血脉凝结而成，常浮现万兽模样，成丹率增加10%，攻击力增加10%",
    obtain: "未知",
    atk: 0.15,
    price: 0,
    recovery: 0,
  },
  {
    name: "玄黄炎",
    type: "fire",
    detail: "异火广场上的深黄色火焰，成丹率增加10%，攻击力增加10%",
    obtain: "未知",
    atk: 0.1,
    price: 250000,
    recovery: 0,
  },
  {
    name: "兽火",
    type: "fire",
    detail: "火属性妖兽产生的兽火，成丹率增加5%，攻击力增加5%",
    obtain: "未知",
    atk: 0.05,
    price: 100000,
    recovery: 0,
  },
];

// 药鼎
const YaoFatherList = [
  {
    name: "混沌圣鼎",
    type: "yaoFather",
    detail: "乃开天辟地时乳育而出，与混沌圣焱同根而生，炼药成丹率增加160%",
    effect: 2.6,
    obtain: "未知",
    price: 0,
    recovery: 0,
  },
  {
    name: "黑冥鼎",
    type: "yaoFather",
    detail: "具体来历不详，据传能吞噬一切火焰，炼药成丹率增加140%",
    effect: 2.4,
    obtain: "未知",
    price: 0,
    recovery: 0,
  },
  {
    name: "紫渊",
    type: "yaoFather",
    detail: "本是一块奇怪的紫色石头，经过吸收上千年的日月精华变成了鼎，炼药成丹率增加120%",
    effect: 2.2,
    obtain: "未知",
    price: 0,
    recovery: 0,
  },
  {
    name: "龙魂",
    type: "yaoFather",
    detail: "相传上古时期由龙族帝王所造，蕴含着龙族精魄所在，炼药成丹率增加90%",
    effect: 1.9,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "虎魄",
    type: "yaoFather",
    detail: "据传是帝级魔兽白虎死后魂魄融入了石头中形成了此鼎，炼药成丹率增加80%",
    effect: 1.8,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "凤鸣",
    type: "yaoFather",
    detail: "乃传说中的圣兽凤凰世代传承留下的精血经过上千年融合乳育而出，炼药成丹率增加70%",
    effect: 1.7,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "圣耀鼎",
    type: "yaoFather",
    detail: "乃世界光明本源分化而出的极一小部分形成，与黑魔相对，炼药成丹率增加60%",
    effect: 1.6,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "黑魔鼎",
    type: "yaoFather",
    detail: "乃世界黑暗本源分化而出的极一小部分形成，与圣耀相对，炼药成丹率增加60%",
    effect: 1.6,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "大地之心",
    type: "yaoFather",
    detail: "由大地自然的敷化形成的鼎，拥有浓郁的土之力，炼药成丹率增加50%",
    effect: 1.5,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "深海之灵",
    type: "yaoFather",
    detail: "本为海底一极度坚硬的珊瑚，经过大海的精华长期乳育从而变成鼎形，炼药成丹率增加40%",
    effect: 1.4,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "陨星",
    type: "yaoFather",
    detail: "由一天外陨石经过高人打造从而形成此鼎，炼药成丹率增加30%",
    effect: 1.3,
    obtain: "活动",
    price: 0,
    recovery: 100,
  },
  {
    name: "炽炎",
    type: "yaoFather",
    detail: "乃一火山奇石，在岩浆中长时间打磨形成鼎，炼药成丹率增加20%",
    effect: 1.2,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "万兽鼎",
    type: "yaoFather",
    detail: "上古时期由人类著名匠师借助魔兽灵魂而打造成功，炼药成丹率增加10%",
    effect: 1.1,
    obtain: "活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "玄铁药鼎",
    type: "yaoFather",
    detail: "村里铁匠打造的药鼎，炼药成丹率增加5%",
    effect: 1.05,
    obtain: "商城",
    price: 400000,
    recovery: 200,
  },
  {
    name: "学徒药鼎",
    type: "yaoFather",
    detail: "拜入星陨阁后赠送的普通药鼎，只能保证基础成丹",
    effect: 1,
    obtain: "拜炼药师为师",
    price: 0,
    recovery: 20,
  },
  {
    name: "破铜药鼎",
    type: "yaoFather",
    detail: "不知哪里来的破铜打造的药鼎，炼药成丹率减少5%",
    effect: 0.95,
    obtain: "历练",
    price: 100000,
    recovery: 50,
  },
];
// 货币
const goldsList = [
  {
    name: "金币",
    type: "golds",
    detail: "基础货币",
    obtain: "历练/出售物品/活动",
    price: 1,
    recovery: 1,
  },
];

// 道具
const propList = [
  {
    name: "免签卡半张",
    type: "prop",
    detail: "集齐两张，可以获得单日免签卡一张",
    obtain: "月卡用户历练/活动",
    price: 0,
    recovery: 0,
  },
  {
    name: "免签卡碎片",
    type: "prop",
    detail: "两日免签卡碎片，据说集齐3片可以兑换两日免签卡一张",
    obtain: "白金月卡用户历练/活动",
    price: 0,
    recovery: 0,
  },
];
export const goods = [...YaoList, ...YaoFatherList, ...FireList, ...StuffList, ...goldsList, ...propList, ...ArmsList, ...ArmorList, ...GongList];
